# +----------------------------------------------------+
# <                 Bot Configuration                  >
# <                                                    >
# <               All bot configuration                >
# +----------------------------------------------------+

# Bot token can be found on your
# Discord application page.
Bot_Token: sample.token

# Bot ID, this is also known as Client ID
# on your Discord application page.
Bot_ID: '123456789'

# Owner ID of the owner of the bot, server, or guild.
# You can easily get your id by right
# clicking your self and copy id.
# This only works when developer mode is enabled.
# Go to settings>appearance and enable developer mode
Owner_ID: '123456789'

# Set of character that distinguish if it's a command.
Command_Trigger: '!!'

# Should bot's command responses be deleted after 5 minutes?
Delete_Response: false

# This will be the game of the bot
# and will be shown under the name
# of the bot as "Playing <Default_Game>"
Default_Game: default

# +----------------------------------------------------+
# <               Plugin Configuration                 >
# <                                                    >
# <               All bot configuration                >
# +----------------------------------------------------+

# This is your support voice channels.
# If someone joins these channels, it will
# send a message to ops in-game.
VoiceChannels:
  - '123123123'
  - '123123123'

# This is your broadcast channels.
# When someone joins your Discord or
# someone synchronize their account
# the bot will send the message here.
SyncChannels:
  - '123456789'
  - '987654321'

# When someone gets banned in-game,
# send a broadcast to these channels.
BanChannels:
  - '12121212'
  - '123123123'

# This will be the logo of the plugin and will be seen when help command
# is executed.
Plugin_Logo: ""
